account/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views as account_views

app_name = 'account'
urlpatterns = [
    path('authenticated/', account_views.CheckAuthenticatedView.as_view()),
    path('logintest/', account_views.LoginView.as_view()),
    path('logouttest/', account_views.LogoutView.as_view()),
    path('csrf_cookie/', account_views.GetCSRFToken.as_view()),
    path('register/', account_views.registration_view, name="register"),
    path('login/', account_views.login_view, name="login"),
    path('logout/', account_views.logout_view, name="logout"),
    path('index/', account_views.index, name="index"),

]

chatsupport/urls.py
'''
    urls.py is used by the project when its accessing any tenant specific schemas
'''

from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('api-auth/', include('rest_framework.urls')),
                  path('accounts/', include('account.urls')),
                  path('chat/', include('chatting.urls')),
                  path('auth/', include('djoser.urls')),
                  path('auth/', include('djoser.urls.jwt')),
                  path('auth/', include('djoser.social.urls')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# urlpatterns += [re_path(r'^.*', TemplateView.as_view(template_name='index.html'))]

chatting/urls.py
from django.urls import path
from . import views
from . import api

app_name = 'chatting'

urlpatterns = [
    path('', views.index, name="index"),
    path('support/', views.admin_index, name="admin_index"),
    path('admin_join_chat/<str:room_id>', views.join_chat, name="admin_join_chat"),
    path('admin_end_chat/<str:room_id>', views.end_chat, name="admin_end_chat"),
    path('support/chat_page/<str:room_id>', views.chat_page, name="chat_page"),
    path('api/create_room/', api.CreateRoomAPI.as_view(), name="create_room"),
    path('api/upload_file/', api.fileUpload, name="upload_file"),
    path('api/download_file/', api.fileDownload, name="download_file"),
    path('api/chatlist/', views.Chatlist.as_view(), name="chatlist"),
    # path('api/latest_room/', views.LatestChatRoom.as_view(), name="latestRoom"),
    path('api/get_messages/', views.GetLastMessages.as_view(), name="getMessages"),
    path('api/join_chat/', views.JoinChat.as_view(), name="joinChat"),



]

chatting/models.py
import json
import uuid

from django.conf import settings
from django.db import models
from account.models import Account
from datetime import datetime
from django.utils.translation import ugettext_lazy as _
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync


# class SupportGroup(models.Model):
#     name = models.CharField(_("name"), max_length=225)
#     agents = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='agent_support_groups')
#     supervisors = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='supervisor_support_groups')
#
#     def __str__(self):
#         return f'{self.name}'
#
#     class Meta:
#         verbose_name = _('Support group')
#         verbose_name_plural = _('Support groups')


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return f"Uploaded_Files/user_{instance.uploaded_by}/{filename}"


class UploadedFile(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    uploaded_by = models.CharField(_("name"), max_length=255, null=True, blank=True)
    file = models.FileField(verbose_name=_("File"), blank=False, null=False, upload_to=user_directory_path)
    upload_date = models.DateTimeField(auto_now_add=True, verbose_name=_("Upload date"))

    def __str__(self):
        return str(self.file.name)

    def get_file_name(self):
        return self.file.name.split("/")[-1]


class RoomManager(models.Manager):
    def get_query_set(self):
        return super(RoomManager, self).get_query_set().filter(ended=None)


class Room(models.Model):
    id = models.UUIDField(primary_key=True,
                          default=uuid.uuid4,
                          editable=False)
    name = models.CharField(_("name"), max_length=255)
    details = models.TextField(blank=True)
    started = models.DateTimeField(auto_now=True)
    ended = models.DateTimeField(null=True, blank=True)
    agents = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name='chats',
                               on_delete=models.CASCADE)
    objects = models.Manager()
    active = RoomManager()
    last_sent_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.started}:{self.name}'

    def end(self):
        self.ended = datetime.now()
        self.save()

    def save(self, updateChatList=True, *args, **kwargs):
        from .serializers import RoomSerializer
        channel_layer = get_channel_layer()
        if updateChatList:
            super(Room, self).save(*args, **kwargs)
            chatStartMsg = Message.objects.create(room=self, message=f'Chat Started', type='started_info')
            preChatFormMsg = Message.objects.create(room=self, name=self.name,  message=self.details, type='chat_form')
            greetingMsg = Message.objects.create(room=self, message=f'Hello, How may I help you?', name='greetingMsg' )
            chatStartMsg.save()
            preChatFormMsg.save()
            greetingMsg.save()

            message = {
                'command': 'update_chat_list',
                'message': {
                    'chatRoom': RoomSerializer(self).data,
                }
            }
            async_to_sync(channel_layer.group_send)(
                'user', {
                    'type': 'chat_message',
                    'message': message
                }
            )
        else:
            super(Room, self).save(*args, **kwargs)

    def get_agents(self):
        return self.agents

    def unread_messages(self):
        total_unread_messages = Message.objects.filter(room=self, agent=None, receiverHasRead=False)
        return total_unread_messages.count()

    def message_read_true(self, sender):
        if sender == 'agent':
            total_unread_messages = Message.objects.filter(room=self, agent__isnull=True, receiverHasRead=False)
        else:
            total_unread_messages = Message.objects.filter(room=self, agent__isnull=False, receiverHasRead=False)
        for i in total_unread_messages:
            i.receiverHasRead = True
        Message.objects.bulk_update(total_unread_messages, ['receiverHasRead'])
        # channel_layer = get_channel_layer()
        # message = {
        #     'command': 'update_chat_list',
        #     'message': 'Successfully updated'
        # }
        # async_to_sync(channel_layer.group_send)(
        #     'user', {
        #         'type': 'chat_message',
        #         'message': message
        #     }
        # )

    def last_message(self):
        last_msg = Message.objects.filter(room=self).order_by('-sent')[:1]
        if last_msg:
            message = last_msg[0].message
            sent_time = last_msg[0].sent

            result = {
                'message': message,
                'sent_time': str(sent_time)
            }
            return result
        else:
            result = {
                'message': 'Compose Message...',
                'sent_time': self.started
            }
            return result

    class Meta:
        verbose_name = _('Chat')
        verbose_name_plural = _('Chats')


class Message(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='messages')
    name = models.CharField(max_length=255, blank=True, null=True)
    agent = models.ForeignKey(Account, on_delete=models.CASCADE, blank=True, null=True)
    message = models.TextField()
    sent = models.DateTimeField(auto_now_add=True)
    receiverHasRead = models.BooleanField(default=False)
    type = models.CharField(default='chat', max_length=50)
    file = models.ForeignKey(UploadedFile, related_name='message', on_delete=models.DO_NOTHING, verbose_name=_("File"),
                             blank=True, null=True)

    def __str__(self):
        return f'{self.sent}: "{self.message}" in Room "{self.room}"'

    def save(self, *args, **kwargs):
        super(Message, self).save(*args, **kwargs)
        room = Room.objects.get(id=self.room.id)
        room.last_sent_time = self.sent
        room.save(updateChatList=False)

    def get_name(self):
        if self.agent:
            return self.agent.firstname or self.agent.Username
        else:
            return self.name

    class Meta:
        verbose_name = _('Chat message')
        verbose_name_plural = _('Chat messages')

chatting/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from chatting.models import Room, Message


class RoomForm(forms.ModelForm):
    details = forms.CharField(widget=forms.Textarea, label=_('Question'))

    class Meta:
        model = Room
        fields = ('name', 'details')


class MessageForm(forms.ModelForm):
    message = forms.CharField()

    class Meta:
        model = Message
        fields = ('message',)

chatting/views.py
from django.shortcuts import render, get_object_or_404
from .forms import RoomForm
from .models import Room, Message, UploadedFile
from django.http import HttpResponseRedirect, JsonResponse
from django.db.models import Q
from rest_framework import permissions
from rest_framework.response import Response
from rest_framework.views import APIView
from django.urls import reverse
from django.contrib.auth import get_user_model
from .serializers import RoomSerializer, MessageSerializer
from account.forms import RegistrationForm
import requests

# Create your views here.
User = get_user_model()


def index(request):
    from django.db import connection
    connection.set_tenant(request.user.tenant)
    room_form = RoomForm(request.POST or None)
    if room_form.is_valid():
        room = room_form.save(commit=False)
        room.save()
        return HttpResponseRedirect(reverse('client_chat_page', args=[room.id]))

    context = {
        'room_form': room_form
    }
    return render(request, 'index.html', context=context)

def join_chat(request, room_id):
    """
    This function lets the support group admin join the chat when he/she clicks the room and redirect him/her to that
    particular room
    """
    room = get_object_or_404(Room, id=room_id)
    if request.user.is_authenticated:
        user = User.objects.get(email=request.user.email)
        room.agents.add(user)
        message = Message()
        name = request.user.first_name or request.user.username
        message.message = '%s has joined the chat' % name
        room.messages.add(message, bulk=False)
    return HttpResponseRedirect(reverse('chatting:chat_page', args=[room.id]))


def end_chat(request, room_id):
    """
    This function lets anyone end the chat and set the ended field in the database model to current time.
    """
    room = get_object_or_404(Room, id=room_id)
    message = Message()
    name = request.user.first_name or request.user.username
    message.message = '%s has left the chat.  This chat has ended.' % name
    room.messages.add(message, bulk=False)
    room.end()
    room.save()
    return HttpResponseRedirect(reverse('chatting:admin_index'))


def chat_page(request, room_id):
    """
    Renders the chat page where users can chat.
    """
    room = Room.objects.get(id=room_id)
    if room.ended:
        return HttpResponseRedirect(reverse("chatting:admin_index"))
    messages = Message.objects.filter(room=room).order_by('sent')
    context = {
        'messages': messages,
        'room': room
    }
    return render(request, 'chat_page.html', context)


# ADMIN

from django.forms.models import model_to_dict
import json

class Chatlist(APIView):
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request, format=None):
        user = request.user
        all_chats = Room.objects.filter(agents=user).order_by('-last_sent_time')
        pending_rooms = Room.objects.filter(ended=None, agents=None).exclude(agents=user).order_by('-started')
        all_room_serializers = RoomSerializer(all_chats, many=True)
        pending_serializers = RoomSerializer(pending_rooms, many=True)
        return Response({
            'all_rooms': all_room_serializers.data,
            'pending_rooms': pending_serializers.data
        })



def admin_index(request):
    """
    This function lists all the chats and the pending chat of the logged in chat support user, and if the logged in user
    the superuser of the tenant, then make him capable of registering new users to his tenant.
    """
    user = request.user
    all_chats = Room.objects.filter(agents=user)
    pending_rooms = Room.objects.filter(ended=None, agents=None).exclude(agents=user).order_by('-started')

    context = {
        'pending_rooms': pending_rooms,
        'all_chats': all_chats,
        'tenant_name': request.tenant.schema_name

    }
    # Let superuser create new users in his tenant and save the newly created user's info in both public schema and the
    # specific tenant schema

    if request.user.is_superuser:
        if request.POST:
            form = RegistrationForm(request.POST)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.save()
                from django_tenants.utils import schema_context
                with schema_context('public'):
                    form = RegistrationForm(request.POST)
                    instance = form.save(commit=False)
                    instance.save()

            else:
                context['registration_form'] = form
        else:
            form = RegistrationForm(initial={
                'tenant': request.tenant,
            })
            context['registration_form'] = form

    return render(request, 'admin_index.html', context)


"""
The following function performs tasks that are self explanatory 
"""


class GetLastMessages(APIView):
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request, format=None):
        chatId = request.GET.get('chat_id')
        room = get_object_or_404(Room, id=chatId)
        room_agent_exists = False
        room_agent_id = None
        if room.agents:
            room_agent_exists = True
            room_agent_id = room.agents.id
        messages = Message.objects.filter(room=room)
        last_10_messages = messages.order_by('-sent').all()[:50]
        serializers = MessageSerializer(last_10_messages, many=True)
        total_unread_messages = room.unread_messages()
        return Response({
            'room_name': room.name,
            'room_id': room.id,
            'last_10_messages': serializers.data,
            'room_agent_exists': room_agent_exists,
            'room_agent': room_agent_id,
            'total_unread_messages': total_unread_messages
        })


class JoinChat(APIView):
    permission_classes = (permissions.IsAuthenticated,)

    def post(self, request, format=None):
        chatId = request.data.get('room_id')
        room = get_object_or_404(Room, id=chatId)
        room.agents = request.user
        # message = Message.objects.create(
        #     room=room,
        #     message=f'{request.user.first_name} has joined the chat',
        #     type='info')
        room.save(updateChatList=False)
        # message.save()
        return Response({
            'chatId': room.id,
            'agentName': room.agents.username,
            'agent': room.agents.id,
            'success': 'Agent added',
        })


def get_user_contact(username):
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        user = None
    return user

def get_current_chat(chatId):
    return get_object_or_404(Room, id=chatId)


def get_room(room_id):
    return Room.objects.get(id=room_id)


def get_file_by_id(file_id):
    return UploadedFile.objects.get(id=file_id)

chatting/templates/admin_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admin Index Page</title>
</head>
<body>
<div class="room_list">
    <h1>Logged In: {{user.username}}</h1>
    <h2>Support Group: {{support_group.name}}</h2>
    <a style="float:right;" href="{% url 'account:logout' %}">Logout</a>
    <h1>Pending Chats:</h1>
    <br>
    <div class="list">
        <ul>
            {% for rooms in pending_rooms %}
            <li><a href="{% url 'chatting:admin_join_chat' rooms.id%}">{{rooms.name}}</a></li>
            {% endfor %}
        </ul>
    </div>
    <h1>All Chats:</h1>
    <br>
    <div class="all_list">
        <ul>
            {% for room in all_chats %}

            <li>{% if not room.ended %}<a href="{% url 'chatting:chat_page' room.id%}">{{room.name}}</a>{% else %}{{room.name}}{% endif %} <span>({% if not room.ended %}Active{% else %}Ended{% endif %})</span></li>
            {% endfor %}
        </ul>
    </div>
</div>
<hr>
{% if registration_form %}
<div class="register">
    <p><h1>Since you are a Superuser of "{{tenant_name}}" tenant, you can register new users to your tenant.</h1></p>
    <div class="form_body">
        <form method="post">
            {% csrf_token %}
            <div class="row justify-content-center">
                <div class="col-md-5">
                    <div class="card">
                        <header class="card-header">
                            <h3 class="card-title mt-2">Create account</h3>
                        </header>
                        <article class="card-body">
                            <div class="form-group">

                                <label>Create {{ registration_form.username.label }}</label><br>

                                {{ registration_form.username }}

                            </div> <!-- form-group end.// -->


                            <div class="form-group">
                                <label>Create {{ registration_form.email.label }}</label><br>
                                {#                                        <input type="email" class="form-control" placeholder="">#}
                                {{ registration_form.email }}
                                <small class="form-text">We'll never share your email with anyone else.</small>
                            </div> <!-- form-group end.// -->
                            <div class="form-group">
                                <label>Create {{ registration_form.first_name.label }}</label><br>
                                {{ registration_form.first_name }}
                            </div>
                            <div class="form-group">
                                <label>Create {{ registration_form.last_name.label }}</label><br>
                                {{ registration_form.last_name }}
                            </div>
                            <div class="form-group" style="display: none">
                                <label>Create {{ registration_form.tenant.label }}</label><br>
                                {{ registration_form.tenant }}
                            </div>

                            <div class="form-group">
                                <label>Create {{ registration_form.password1.label }}</label><br>
                                {{ registration_form.password1 }}
                            </div> <!-- form-group end.// -->
                            <div class="form-group">
                                <label>{{ registration_form.password2.label }}</label><br>
                                {{ registration_form.password2 }}
                            </div> <!-- form-group end.// -->
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary btn-block"> Register</button>
                            </div> <!-- form-group// -->
                            <small>By clicking the 'Sign Up' button, you confirm that you accept our <br> Terms
                                of use
                                and Privacy Policy.</small>

                        </article> <!-- card-body end .// -->
                        <div class="border-top card-body text-center">Have an account? <a href="{% url 'account:login'}">Log
                            In</a>
                        </div>
                    </div> <!-- card.// -->
                </div> <!-- col.//-->
            </div> <!-- row.//-->

            <!--container end.//-->

        </form>
    </div>
</div>
{% endif %}
<!-- Start of LiveChat (www.livechatinc.com) code -->
<script>
    window.__lc = window.__lc || {};
    window.__lc.license = 13536741;
    ;(function(n,t,c){function i(n){return e._h?e._h.apply(null,n):e._q.push(n)}var e={_q:[],_h:null,_v:"2.0",on:function(){i(["on",c.call(arguments)])},once:function(){i(["once",c.call(arguments)])},off:function(){i(["off",c.call(arguments)])},get:function(){if(!e._h)throw new Error("[LiveChatWidget] You can't use getters before load.");return i(["get",c.call(arguments)])},call:function(){i(["call",c.call(arguments)])},init:function(){var n=t.createElement("script");n.async=!0,n.type="text/javascript",n.src="https://cdn.livechatinc.com/tracking.js",t.head.appendChild(n)}};!n.__lc.asyncInit&&e.init(),n.LiveChatWidget=n.LiveChatWidget||e}(window,document,[].slice))
</script>
<noscript><a href="https://www.livechatinc.com/chat-with/13536741/" rel="nofollow">Chat with us</a>, powered by <a href="https://www.livechatinc.com/?welcome" rel="noopener nofollow" target="_blank">LiveChat</a></noscript>
<!-- End of LiveChat code -->


</body>
</html>