account/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views as account_views

app_name = 'account'
urlpatterns = [
    path('authenticated/', account_views.CheckAuthenticatedView.as_view()),
    path('logintest/', account_views.LoginView.as_view()),
    path('logouttest/', account_views.LogoutView.as_view()),
    path('csrf_cookie/', account_views.GetCSRFToken.as_view()),
    path('register/', account_views.registration_view, name="register"),
    path('login/', account_views.login_view, name="login"),
    path('logout/', account_views.logout_view, name="logout"),
    path('index/', account_views.index, name="index"),

]

chatsupport/urls.py
'''
    urls.py is used by the project when its accessing any tenant specific schemas
'''

from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('api-auth/', include('rest_framework.urls')),
                  path('accounts/', include('account.urls')),
                  path('chat/', include('chatting.urls')),
                  path('auth/', include('djoser.urls')),
                  path('auth/', include('djoser.urls.jwt')),
                  path('auth/', include('djoser.social.urls')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# urlpatterns += [re_path(r'^.*', TemplateView.as_view(template_name='index.html'))]

tenants/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from . import api

app_name = 'tenants'

urlpatterns = [
    path('create-tenant/', views.create_tenant, name='create_tenant'),
    path('register_tenant/', views.RegisterTenantView.as_view(), name='register_tenant'),

    path('api/get_tenant_uuid/', api.GetTokenUUID.as_view(), name='get-tenant-uuid'),

]

account/models.py
import uuid

from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from tenants import models as tenant_model


# For Authentication
class MyAccountManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError("Users must have an Email address")
        if not username:
            raise ValueError("User must have a Username")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password):
        user = self.create_user(
            username=username,
            email=self.normalize_email(email),
            password=password,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)


# User Model
class Account(AbstractBaseUser):
    user_id = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username = models.CharField(max_length=30, unique=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    tenant = models.ForeignKey(tenant_model.Client, on_delete=models.CASCADE, default=1)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name="Last login", auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', ]

    objects = MyAccountManager()

    def set_tenant(self, tenant_name):
        tenant = tenant_model.Client.objects.get(schema_name=tenant_name)
        self.tenant = tenant

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_level):
        return True

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

from .models import Account


class RegistrationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget = forms.PasswordInput(
            attrs={'placeholder': 'Password', 'class': 'form-control'})
        self.fields['password2'].widget = forms.PasswordInput(
            attrs={'placeholder': 'Confirm Password', 'class': 'form-control'})

    class Meta:
        model = Account
        fields = ('email', 'username', 'first_name', 'last_name', 'tenant', 'password1', 'password2')

        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}),
        }


class AccountAuthenticationForm(forms.ModelForm):
    password = forms.CharField(label='Passsword',
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))

    class Meta:
        model = Account
        fields = ('email', 'password')

        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'})
        }

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError("Invalid login")

account/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import login, authenticate, logout
from .forms import RegistrationForm
from .forms import AccountAuthenticationForm
from django.http import HttpResponseRedirect
from rest_framework.views import APIView
from django.views.decorators.csrf import ensure_csrf_cookie, csrf_protect, csrf_exempt
from django.utils.decorators import method_decorator
from rest_framework import permissions
from rest_framework.response import Response
from django.contrib import auth


@method_decorator(ensure_csrf_cookie, name='dispatch')
class GetCSRFToken(APIView):
    permission_classes = (permissions.AllowAny,)

    def get(self, request, format=None):
        return Response({'success': 'CSRF cookie set'})


@method_decorator(csrf_exempt, name='dispatch')
class CheckAuthenticatedView(APIView):
    def get(self, format=None):
        user = self.request.user

        try:
            isAuthenticated = user.is_authenticated

            if isAuthenticated:
                return Response({'isAuthenticated': 'success'})
            else:
                return Response({'isAuthenticated': 'error'})

        except:
            return Response({'error': 'Something went wrong when checking authentication status'})


# @method_decorator(csrf_protect, name='dispatch')
class LoginView(APIView):
    permission_classes = (permissions.AllowAny,)

    def post(self, request, format=None):
        data = self.request.data
        email = data['email']
        password = data['password']

        try:
            user = auth.authenticate(email=email, password=password)
            if user is not None:
                auth.login(request, user)
                print(user.tenant.tenant_uuid)
                tenant_uuid = user.tenant.tenant_uuid
                request.session['tenant_uuid'] = str(tenant_uuid)
                return Response({
                    'success': 'User Authenticated',
                    'tenant_uuid': str(tenant_uuid)
                })
            else:
                return Response({
                    'error': 'Error Authenticating'
                })
        except:
            return Response({'error': 'Something went wrong when logging in'})


class LogoutView(APIView):
    def post(self, request, format=None):
        try:
            auth.logout(request)
            return Response({'success': 'Logged Out'})
        except:
            return Response({'error': 'Something went wrong when logging out'})


def registration_view(request):
    context = {}
    if request.POST:
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            account = authenticate(email=email, password=raw_password)
            login(request, account)
            return redirect('account:login')
        else:
            context['registration_form'] = form
    else:
        form = RegistrationForm()
        context['registration_form'] = form
    context['tenant_name'] = request.tenant
    return render(request, 'register.html', context)


def logout_view(request):
    logout(request)
    return redirect('/')


def login_view(request):
    context = {}
    user = request.user
    if user.is_authenticated:
        return HttpResponseRedirect(reverse("chatting:admin_index"))
    if request.POST:
        form = AccountAuthenticationForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email=email, password=password)
            if user:
                login(request, user)
                request.session['tenant_uuid'] = str(user.tenant.tenant_uuid)
            # print('login session',request.session)

            return redirect(reverse("account:index"))
    else:
        form = AccountAuthenticationForm()

    context['login_form'] = form
    return render(request, 'login.html', context)


# REDIRECT TO TENANT APPS
def index(request):
    # print('index session',request.session.keys())
    return redirect(reverse("chatting:admin_index"))

account/templates/index_a.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tenant {{tenant.schema_name}}</title>
</head>
<body style="margin: 30px;">
<!--<h3>Number of logins: {{num_login}}</h3>-->
<h3>Tenant: {{tenant.schema_name}}</h3>
<a style="float: right" href="{% url 'account:logout' %}">Logout</a>
<div class="users">
  <ul>
    {% for i in users %}
      <li>{{i.email}}</li>
    {% endfor %}
  </ul>
</div>
<hr>
{% if registration_form %}
<div class="register">
    <p><h1>Since you are a Superuser of "{{tenant.schema_name}}" tenant, you can register new users to your tenant.</h1></p>
    <div class="form_body">
        <form method="post">
            {% csrf_token %}
                <div class="row justify-content-center">
                    <div class="col-md-5">
                        <div class="card">
                            <header class="card-header">
                                <h3 class="card-title mt-2">Create account</h3>
                            </header>
                            <article class="card-body">
                                <div class="form-group">

                                    <label>Create {{ registration_form.username.label }}</label><br>

                                    {{ registration_form.username }}

                                </div> <!-- form-group end.// -->


                                <div class="form-group">
                                    <label>Create {{ registration_form.email.label }}</label><br>
                                    {#                                        <input type="email" class="form-control" placeholder="">#}
                                    {{ registration_form.email }}
                                    <small class="form-text">We'll never share your email with anyone else.</small>
                                </div> <!-- form-group end.// -->
                                <div class="form-group">
                                    <label>Create {{ registration_form.first_name.label }}</label><br>
                                    {{ registration_form.first_name }}
                                </div>
                                <div class="form-group">
                                    <label>Create {{ registration_form.last_name.label }}</label><br>
                                    {{ registration_form.last_name }}
                                </div>
                                <div class="form-group" style="display: none">
                                    <label>Create {{ registration_form.tenant.label }}</label><br>
                                    {{ registration_form.tenant }}
                                </div>

                                <div class="form-group">
                                    <label>Create {{ registration_form.password1.label }}</label><br>
                                    {{ registration_form.password1 }}
                                </div> <!-- form-group end.// -->
                                <div class="form-group">
                                    <label>{{ registration_form.password2.label }}</label><br>
                                    {{ registration_form.password2 }}
                                </div> <!-- form-group end.// -->
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary btn-block"> Register</button>
                                </div> <!-- form-group// -->
                                <small>By clicking the 'Sign Up' button, you confirm that you accept our <br> Terms
                                    of use
                                    and Privacy Policy.</small>

                            </article> <!-- card-body end .// -->
                            <div class="border-top card-body text-center">Have an account? <a href="{% url 'account:login'}">Log
                                In</a>
                            </div>
                        </div> <!-- card.// -->
                    </div> <!-- col.//-->
                </div> <!-- row.//-->

            <!--container end.//-->

        </form>
    </div>
</div>
{% endif %}
</body>
</html>

account/templates/login.html
<div class="body_2">
    {% if messages%}
    {% for message in messages %}
    <div class="alert alert-success" role="alert" id="#messages">
        {{ message }}
        <button class="close" id="#close" onclick="close_msg()">X</button>
    </div>
    {% endfor %}
    {% endif %}
    <form method="post">
        {% csrf_token %}

        <div class="container">
            <div class="d-flex justify-content-center h-100">
                <div class="card">
                    <div class="card-header">
                        <h3>Sign In</h3>
                        <div class="d-flex justify-content-end social_icon">
                            <span><i class="fa fa-facebook-square"></i></span>
                            <span><i class="fa fa-google-plus-square"></i></span>
                            <span><i class="fa fa-twitter-square"></i></span>
                        </div>
                    </div>
                    <div class="card-body">

                        <div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fa fa-user"></i></span>
                            </div>
                            {# <input type="text" class="form-control" placeholder="email">#}
                            {{ login_form.email }}
                            {% if login_form.email.help_text %}#}
                            <small style="color: grey;">{{ login_form.email.help_text }}</small>
                            {% endif %}

                        </div>
                        <div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fa fa-key"></i></span>
                            </div>
                            {# <input type="password" class="form-control" placeholder="password">#}
                            {{ login_form.password }}<br>
                            {% if login_form.password.help_text %}
                            <small style="color: grey;">{{ login_form.password.help_text }}</small>
                            {% endif %}
                        </div>
                        <div class="row align-items-center remember">
                            <input type="checkbox">Remember Me
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Login" class="btn float-right login_btn">
                        </div>
                        {% for field in login_form %}
                        {% for error in field.errors %}
                        <p style="color: red;">{{ error }}</p>
                        {% endfor %}
                        {% endfor %}
                        {% if login_form.non_field_errors %}
                        <div style="color: red;font-size: 20px;">
                            <span>{{ login_form.non_field_errors }}</span>
                        </div>
                        {% endif %}
                    </div>
                    <div class="card-footer">
                        <div class="d-flex justify-content-center links">
                            Don't have an account?<a href="{% url 'account:register'%}">Sign Up</a>
                        </div>
                        <div class="d-flex justify-content-center">
                            <a href="#" style="color: white">Forgot your password?</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </form>
</div>
<style>
    @import url("https://fonts.googleapis.com/css?family=Numans");

    .body_2 {
        background-size: cover;
        background-repeat: no-repeat;
        height: 100%;
        font-family: "Numans", sans-serif;
    }

    .container {
        height: 457px;
        margin-top: 100px;
        align-content: center;
    }

    .card {
        height: 370px;
        margin-top: auto;
        margin-bottom: auto;
        width: 400px;
        background-color: rgba(0, 0, 0, 0.5) !important;
    }

    .social_icon span {
        font-size: 60px;
        margin-left: 10px;
        color: #ffc312;
    }

    .social_icon span:hover {
        color: white;
        cursor: pointer;
    }

    .card-header h3 {
        color: white;
    }

    .social_icon {
        position: absolute;
        right: 20px;
        top: -45px;
    }

    .input-group-prepend span {
        width: 50px;
        background-color: #ffc312;
        color: black;
        border: 0 !important;
    }

    input:focus {
        outline: 0 0 0 0 !important;
        box-shadow: 0 0 0 0 !important;
    }

    .remember {
        color: white;
    }

    .remember input {
        width: 20px;
        height: 20px;
        margin-left: 15px;
        margin-right: 5px;
    }

    .login_btn {
        color: black;
        background-color: #ffc312;
        width: 100px;
    }

    .login_btn:hover {
        color: black;
        background-color: white;
    }

    .links {
        color: white;
    }

    .links a {
        margin-left: 4px;
    }
</style>

account/templates/main_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>VolgAI Chat</title>
</head>
<body>
<div class="create">
    <p><h1>Want to create a new tenant? <a href="{% url 'tenants:create_tenant' %}">Register here </a></h1></p>
    <p><h1>Already have a user account?<a href="{% url 'account:login' %}">Log In </a></h1></p>
</div>
  <div class="tenants">
    <ul>
      {% for tenant in tenants %}
      <li><a href="{% url 'account:login'%}">{{tenant.schema_name}}</a></li>
      {% endfor %}
    </ul>
  </div>
</body>
</html>

account/templates/register.html
<h1>Tenant Name: {{tenant_name}}</h1>
    <div class="body_1">
        <form method="post">
            {% csrf_token %}
            <div class="container">
                <br>
                <h1 class="text-center"  style="color: white; font-family: Arial, sans-serif">BRS Registration</h1>
                <hr>

                <div class="row justify-content-center">
                    <div class="col-md-5">
                        <div class="card">
                            <header class="card-header">
                                <a href="{% url 'account:login' tenant_name%}" class="float-right btn btn-outline-primary mt-1" style="color: white; border-color: white" >Sign-in</a>
                                <h3 class="card-title mt-2">Create account</h3>
                            </header>
                            <article class="card-body">
                                <div class="form-group">

                                    <label>Create {{ registration_form.username.label }}</label><br>

                                    {{ registration_form.username }}

                                </div> <!-- form-group end.// -->


                                <div class="form-group">
                                    <label>Create {{ registration_form.email.label }}</label><br>
                                    {#                                        <input type="email" class="form-control" placeholder="">#}
                                    {{ registration_form.email }}
                                    <small class="form-text">We'll never share your email with anyone else.</small>
                                </div> <!-- form-group end.// -->
                                <div class="form-group">
                                    <label>Create {{ registration_form.first_name.label }}</label><br>
                                    {{ registration_form.first_name }}
                                </div>
                                <div class="form-group">
                                    <label>Create {{ registration_form.last_name.label }}</label><br>
                                    {{ registration_form.last_name }}
                                </div>
                                <div class="form-group">
                                    <label>Create {{ registration_form.tenant.label }}</label><br>
                                    {{ registration_form.tenant}}
                                </div>
                                <div class="form-group">
                                    <label>Create {{ registration_form.password1.label }}</label><br>
                                    {{ registration_form.password1 }}
                                </div> <!-- form-group end.// -->
                                <div class="form-group">
                                    <label>{{ registration_form.password2.label }}</label><br>
                                    {{ registration_form.password2 }}
                                </div> <!-- form-group end.// -->
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary btn-block"> Register</button>
                                </div> <!-- form-group// -->
                                <small>By clicking the 'Sign Up' button, you confirm that you accept our <br> Terms
                                    of use
                                    and Privacy Policy.</small>

                            </article> <!-- card-body end .// -->
                            <div class="border-top card-body text-center">Have an account? <a href="{% url 'account:login' tenant_name%}">Log
                                In</a>
                            </div>
                        </div> <!-- card.// -->
                    </div> <!-- col.//-->
                </div> <!-- row.//-->
            </div>
            <!--container end.//-->

        </form>
    </div>
    <style>
        .body_1 {

            background-size: cover;
            background-repeat: no-repeat;
            height: 100%;
            font-family: "Numans", sans-serif;
        }

        .container {
            height: 740px;
            margin-top: 90px;
            align-content: center;
        }

        .card {
            background-color: rgba(0, 0, 0, 0.5) !important;
            color: white;
        }

    </style>